---
title: "The DSCI 100 Code of Conduct"
output: html_document
---

### Introduction
For DSCI 100, we are committed to creating a friendly and respectful place for learning, teaching and contributing. 
All participants in our course and communications are expected to show respect and courtesy to others.

To make clear what is expected, everyone participating in DSCI 100 activities is required to conform to the Code of Conduct. 
This Code of Conduct applies to all spaces managed by DSCI 100 including, but not limited to, class meetings, email communication, and online forums such as Piazza and GitHub. The DSCI 100 teaching team are expected to assist with the enforcement of the Code of Conduct.

The DSCI 100 Instructor is responsible for enforcing the Code of Conduct. They can be contacted by emailing tiffany.timbers@stat.ubc.ca. All reports will be reviewed by the Instructor and will be kept confidential.

### The DSCI 100 Code of Conduct
For DSCI 100, we are dedicated to providing a welcoming and supportive environment for all people, regardless of background or identity. As such, we do not tolerate behaviour that is disrespectful to our teachers or learners or that excludes, intimidates, or causes discomfort to others. We do not tolerate discrimination or harassment based on characteristics that include, but are not limited to, gender identity and expression, sexual orientation, disability, physical appearance, body size, citizenship, nationality, ethnic or social origin, pregnancy, familial status, veteran status, genetic information, religion or belief (or lack thereof), membership of a national minority, property, age, education, socio-economic status, technical choices, and experience level.

Everyone who participates in DSCI 100 activities is required to conform to this Code of Conduct. It applies to all spaces managed by DSCI 100 including, but not limited to, class meetings, email communication, and online forums such as Piazza and GitHub. The DSCI 100 teaching team are expected to assist with the enforcement of the Code of Conduct. 

#### 2.1 Expected Behavior

All participants in our events and communications are expected to show respect and courtesy to others. All interactions should be professional regardless of platform: either online or in-person. In order to foster a positive and professional learning environment we encourage the following kinds of behaviours in all DSCI 100 events and platforms:

- Use welcoming and inclusive language
- Be respectful of different viewpoints and experiences
- Gracefully accept constructive criticism
- Focus on what is best for the community
- Show courtesy and respect towards other community members

Note: See the [four social rules](https://www.recurse.com/manual#sub-sec-social-rules) for further recommendations.

#### 2.2 Unacceptable Behavior

Examples of unacceptable behavior by participants at any DSCI 100 event/platform include:

- written or verbal comments which have the effect of excluding people on the basis of membership of any specific group
- causing someone to fear for their safety, such as through stalking, following, or intimidation
- violent threats or language directed against another person
- the display of sexual or violent images
- unwelcome sexual attention
- nonconsensual or unwelcome physical contact
- sustained disruption of talks, events or communications
- insults or put downs
- sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes
- excessive swearing
- incitement to violence, suicide, or self-harm
- continuing to initiate interaction (including photography or recording) with someone after being asked to stop
publication of private communication without consent

#### 2.3 Consequences of Unacceptable Behavior

Participants who are asked to stop any inappropriate behavior are expected to comply immediately. This applies to any DSCI 100 events and platforms, either online or in-person. If a participant engages in behavior that violates this code of conduct, the teaching team may warn the offender and or engage the DSCI 100 Instructor to investigate the Code of Conduct violation and impose appropriate sanctions.

### Incident Reporting Guidelines

#### Contact points
If someone violates the Code of Conduct during a DSCI 100 event we ask that you report it to a member of the teaching team. The person you have talked to should make a report to the DSCI 100 Instructor about the incident by emailing tiffany.timbers@stat.ubc.ca. If this is not possible for some reason, we would be very grateful if you could report the incident yourself.

If a violation occurs in an online space outside of organised events, please email tiffany.timbers@stat.ubc.ca about the incident.

#### 1.2 Alternate contact points

An email to tiffany.timbers@stat.ubc.ca will be seen by Tiffany Timbers, who is the current instructor of DSCI 100. To report a DSCI 100 code of conduct violation that will not be seen by Tiffany Timbers, an alternative contact person is Bruce Dunham, Professor of Teaching in the Department of Statistics at UBC. His email is: b.dunham@stat.ubc.ca

## Attribution 
- Derived from the [Carpentries Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html)
